spring:
  application.name: later
  main.banner-mode: OFF
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    username: "dbuser"
    password: "12345"
    url: "jdbc:postgresql://localhost:5432/later"
    driver-class-name: "org.postgresql.Driver"